name: Build and push a release without :latest

on:
  push:
    branches:
      - 'release-[0-9]*'
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*-beta*'
      - 'v[0-9]*.[0-9]*.[0-9]*-alpha*'
      - 'v[0-9]*.[0-9]*.[0-9]*-rc*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Push to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TAG_LATEST: "true"
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        make push
        docker logout
